webui/app/blueprints/database/__init__.py
from flask import Blueprint

data_bp = Blueprint("database", __name__)

from . import forms, routes

webui/app/blueprints/database/routes.py
import yaml
import json
from flask import render_template, redirect, request, url_for, current_app

from ... import client
from . import data_bp


@data_bp.route("/", methods=["GET"])
def index():
    return render_template("index.html")

@data_bp.route("/list", methods=["GET"])
def list_databases():
    databases = client.nosql.list()
    return render_template("database/list.html", databases=databases)

@data_bp.route("/<database_name>/", methods=["GET"])
def show_database(database_name):
    collections = client.nosql[database_name].list()
    return render_template("database/database.html", database_name=database_name, collections=collections)

@data_bp.route("/<database_name>/<collection_name>", methods=["GET"])
def show_collection(database_name, collection_name):
    documents = client.nosql[database_name][collection_name].data
    try:
        documents = [yaml.dump(document) for document in json.loads(documents)]
    except:
        documents = ["Error: Unable to parse JSON"]
    return render_template("database/collection.html", database_name=database_name, collection_name=collection_name, documents=documents)

webui/app/templates/database/collection.html
{% extends "_base.html" %}

{% block nav %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('database.list_databases') }}">Databases</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('database.show_database', database_name=database_name) }}">{{ database_name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ collection_name }}</li>
  </ol>
</nav>

{% endblock %}


{% block content %}

<h2>Collection <span class="badge bg-secondary">{{ database_name }}/{{ collection_name }}</span></h2>
<h3>Documents</h3>

<ul class="list-group">
  {% for document in documents %}
  <li class="list-group-item"><pre>{{ document }}</pre></li>
  {% endfor %}
</ul>

{% endblock %}

webui/app/templates/database/database.html
{% extends "_base.html" %}

{% block nav %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
    <li class="breadcrumb-item"><a href="{{ url_for('database.list_databases') }}">Databases</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ database_name }}</li>
  </ol>
</nav>

{% endblock %}


{% block content %}

<h2>Database <span class="badge bg-secondary">{{ database_name }}</span></h2>
<h3>Collections</h3>
<ul class="list-group">
  {% for collection in collections %}
  <li class="list-group-item"><a href="{{ url_for('database.show_collection', database_name=database_name, collection_name=collection) }}">{{ collection }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

webui/app/templates/database/list.html
{% extends "_base.html" %}

{% block nav %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ url_for('main.index') }}">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Databases</li>
  </ol>
</nav>

{% endblock %}

{% block content %}
<h2>Databases</h2>
<ul class="list-group">
  {% for database in databases %}
  <li class="list-group-item"><a href="{{ url_for('database.show_database', database_name=database) }}">{{ database }}</a></li>
  {% endfor %}
</ul>

{% endblock %}